.pragma library

const english = {
    "subtitle": "Focused media conversion for macOS",
    "chooseMedia": "Choose media",
    "changeSource": "Change source",
    "clearSource": "Clear source",
    "settings": "Settings",
    "dropTitle": "Drop a media file here",
    "dropReplaceTitle": "Drop to replace the current media",
    "dropDetail": "or choose one from your Mac",
    "loading": "Inspecting media…",
    "source": "Source",
    "format": "Format",
    "duration": "Duration",
    "size": "Size",
    "video": "Video",
    "audio": "Audio",
    "none": "None",
    "previewUnavailable": "Preview is unavailable, but this file can still be converted.",
    "selection": "Selection",
    "start": "Start",
    "end": "End",
    "current": "Current",
    "setStart": "Set Start",
    "setEnd": "Set End",
    "reset": "Reset",
    "playSelection": "Play Selection",
    "output": "Output",
    "destination": "Destination",
    "quality": "MP3 quality",
    "browse": "Browse…",
    "convert": "Convert",
    "cancel": "Cancel",
    "videoWithAudio": "MP4 · H.264 + AAC",
    "videoOnly": "MP4 · H.264 video",
    "audioOnly": "MP3 audio",
    "high": "High · 256 kbps",
    "medium": "Medium · 192 kbps",
    "low": "Low · 128 kbps",
    "preparing": "Preparing…",
    "running": "Converting…",
    "completed": "Completed",
    "cancelled": "Cancelled",
    "failed": "Conversion failed",
    "language": "Language",
    "system": "System default",
    "english": "English",
    "traditionalChinese": "繁體中文",
    "backend": "Media backend",
    "close": "Close",
    "overwrite": "The destination already exists. Replace it after conversion succeeds?",
    "closeActive": "Cancel the active conversion and close MediaForge?",
    "unsupportedInput": "No supported audio or video stream was found.",
    "cannotOpenInput": "The selected file could not be opened.",
    "decodeFailed": "The media stream could not be decoded.",
    "encoderUnavailable": "A required encoder is unavailable.",
    "invalidTrimRange": "Choose an end time after the start time.",
    "outputExists": "The destination already exists.",
    "outputCreateFailed": "The destination could not be created.",
    "diskWriteFailed": "The output could not be written.",
    "jobActive": "Another media operation is already active.",
    "jobNotFound": "The conversion is no longer active.",
    "unexpected": "An unexpected media error occurred."
};

const traditionalChinese = {
    "subtitle": "專注、輕巧的 macOS 媒體轉檔工具",
    "chooseMedia": "選擇媒體",
    "changeSource": "更換來源",
    "clearSource": "清除來源",
    "settings": "設定",
    "dropTitle": "將媒體檔拖放至此",
    "dropReplaceTitle": "拖放以取代目前媒體",
    "dropDetail": "或從 Mac 選擇檔案",
    "loading": "正在分析媒體…",
    "source": "來源",
    "format": "格式",
    "duration": "長度",
    "size": "大小",
    "video": "影像",
    "audio": "音訊",
    "none": "無",
    "previewUnavailable": "無法在此預覽，但仍可轉換這個檔案。",
    "selection": "選取範圍",
    "start": "開始",
    "end": "結束",
    "current": "目前位置",
    "setStart": "設為起點",
    "setEnd": "設為終點",
    "reset": "重設",
    "playSelection": "播放選取範圍",
    "output": "輸出",
    "destination": "目的地",
    "quality": "MP3 品質",
    "browse": "瀏覽…",
    "convert": "開始轉檔",
    "cancel": "取消",
    "videoWithAudio": "MP4 · H.264 + AAC",
    "videoOnly": "MP4 · H.264 影像",
    "audioOnly": "MP3 音訊",
    "high": "高 · 256 kbps",
    "medium": "中 · 192 kbps",
    "low": "低 · 128 kbps",
    "preparing": "準備中…",
    "running": "轉檔中…",
    "completed": "轉檔完成",
    "cancelled": "已取消",
    "failed": "轉檔失敗",
    "language": "語言",
    "system": "跟隨系統",
    "english": "English",
    "traditionalChinese": "繁體中文",
    "backend": "媒體後端",
    "close": "關閉",
    "overwrite": "目的檔已存在。要在轉檔成功後取代它嗎？",
    "closeActive": "要取消目前的轉檔並關閉 MediaForge 嗎？",
    "unsupportedInput": "找不到支援的影像或音訊串流。",
    "cannotOpenInput": "無法開啟選取的檔案。",
    "decodeFailed": "無法解碼媒體串流。",
    "encoderUnavailable": "需要的編碼器無法使用。",
    "invalidTrimRange": "結束時間必須晚於開始時間。",
    "outputExists": "目的檔已存在。",
    "outputCreateFailed": "無法建立目的檔。",
    "diskWriteFailed": "無法寫入輸出檔案。",
    "jobActive": "已有另一個媒體工作正在執行。",
    "jobNotFound": "這個轉檔工作已不在執行中。",
    "unexpected": "處理媒體時發生未預期的錯誤。"
};

function resolveLanguage(preference, systemLanguage) {
    if (preference === "en" || preference === "zh-TW")
        return preference;
    return String(systemLanguage).toLowerCase().startsWith("zh") ? "zh-TW" : "en";
}

function text(key, language) {
    const catalog = language === "zh-TW" ? traditionalChinese : english;
    return catalog[key] || english[key] || key;
}
