[workspace]
members = [
  "crates/mediaforge-application",
  "crates/mediaforge-core",
  "crates/mediaforge-ffmpeg",
  "crates/mediaforge-flutter-bridge",
  "crates/mediaforge-qt",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
rust-version = "1.88"

[workspace.dependencies]
mediaforge-core = { path = "crates/mediaforge-core" }
mediaforge-ffmpeg = { path = "crates/mediaforge-ffmpeg" }
mediaforge-application = { path = "crates/mediaforge-application" }
flutter_rust_bridge = "=2.12.0"
thiserror = "2"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
