// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'api/handshake.dart';
import 'api/media.dart';
import 'frb_generated.dart';

abstract class MediaForgeRustLibApiImplPlatform
    extends BaseApiImpl<MediaForgeRustLibWire> {
  MediaForgeRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  RustStreamSink<BridgeEvent> dco_decode_StreamSink_bridge_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioStreamInfoDto dco_decode_audio_stream_info_dto(dynamic raw);

  @protected
  BackendCapabilitiesDto dco_decode_backend_capabilities_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AudioStreamInfoDto dco_decode_box_autoadd_audio_stream_info_dto(dynamic raw);

  @protected
  BridgeHandshakeRequest dco_decode_box_autoadd_bridge_handshake_request(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  VideoStreamInfoDto dco_decode_box_autoadd_video_stream_info_dto(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeErrorCode dco_decode_bridge_error_code(dynamic raw);

  @protected
  BridgeEvent dco_decode_bridge_event(dynamic raw);

  @protected
  BridgeEventKind dco_decode_bridge_event_kind(dynamic raw);

  @protected
  BridgeHandshake dco_decode_bridge_handshake(dynamic raw);

  @protected
  BridgeHandshakeRequest dco_decode_bridge_handshake_request(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<MediaOutputMode> dco_decode_list_media_output_mode(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MediaBridgeError dco_decode_media_bridge_error(dynamic raw);

  @protected
  MediaBridgeErrorCode dco_decode_media_bridge_error_code(dynamic raw);

  @protected
  MediaInfoDto dco_decode_media_info_dto(dynamic raw);

  @protected
  MediaOutputMode dco_decode_media_output_mode(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AudioStreamInfoDto? dco_decode_opt_box_autoadd_audio_stream_info_dto(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  VideoStreamInfoDto? dco_decode_opt_box_autoadd_video_stream_info_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoStreamInfoDto dco_decode_video_stream_info_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  RustStreamSink<BridgeEvent> sse_decode_StreamSink_bridge_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioStreamInfoDto sse_decode_audio_stream_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  BackendCapabilitiesDto sse_decode_backend_capabilities_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AudioStreamInfoDto sse_decode_box_autoadd_audio_stream_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHandshakeRequest sse_decode_box_autoadd_bridge_handshake_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VideoStreamInfoDto sse_decode_box_autoadd_video_stream_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeErrorCode sse_decode_bridge_error_code(SseDeserializer deserializer);

  @protected
  BridgeEvent sse_decode_bridge_event(SseDeserializer deserializer);

  @protected
  BridgeEventKind sse_decode_bridge_event_kind(SseDeserializer deserializer);

  @protected
  BridgeHandshake sse_decode_bridge_handshake(SseDeserializer deserializer);

  @protected
  BridgeHandshakeRequest sse_decode_bridge_handshake_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<MediaOutputMode> sse_decode_list_media_output_mode(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MediaBridgeError sse_decode_media_bridge_error(SseDeserializer deserializer);

  @protected
  MediaBridgeErrorCode sse_decode_media_bridge_error_code(
    SseDeserializer deserializer,
  );

  @protected
  MediaInfoDto sse_decode_media_info_dto(SseDeserializer deserializer);

  @protected
  MediaOutputMode sse_decode_media_output_mode(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AudioStreamInfoDto? sse_decode_opt_box_autoadd_audio_stream_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VideoStreamInfoDto? sse_decode_opt_box_autoadd_video_stream_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoStreamInfoDto sse_decode_video_stream_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_bridge_event_Sse(
    RustStreamSink<BridgeEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_stream_info_dto(
    AudioStreamInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_backend_capabilities_dto(
    BackendCapabilitiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_audio_stream_info_dto(
    AudioStreamInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_handshake_request(
    BridgeHandshakeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_video_stream_info_dto(
    VideoStreamInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error_code(
    BridgeErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_event(BridgeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_event_kind(
    BridgeEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_handshake(
    BridgeHandshake self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_handshake_request(
    BridgeHandshakeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_output_mode(
    List<MediaOutputMode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_bridge_error(
    MediaBridgeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_bridge_error_code(
    MediaBridgeErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_info_dto(MediaInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_media_output_mode(
    MediaOutputMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_audio_stream_info_dto(
    AudioStreamInfoDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_video_stream_info_dto(
    VideoStreamInfoDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_stream_info_dto(
    VideoStreamInfoDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class MediaForgeRustLibWire implements BaseWire {
  /// The symbols are looked up in [dynamicLibrary].
  MediaForgeRustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  factory MediaForgeRustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      MediaForgeRustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;
}
