// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/handshake.dart';
import 'api/media.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class MediaForgeRustLib
    extends
        BaseEntrypoint<
          MediaForgeRustLibApi,
          MediaForgeRustLibApiImpl,
          MediaForgeRustLibWire
        > {
  MediaForgeRustLib._();
  @internal
  static final instance = MediaForgeRustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    MediaForgeRustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required MediaForgeRustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<MediaForgeRustLibApiImpl, MediaForgeRustLibWire>
  get apiImplConstructor => MediaForgeRustLibApiImpl.new;

  @override
  WireConstructor<MediaForgeRustLibWire> get wireConstructor =>
      MediaForgeRustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiHandshakeInitializeBridge();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 688988532;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mediaforge_flutter_bridge',
        ioDirectory: '../crates/mediaforge-flutter-bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class MediaForgeRustLibApi extends BaseApi {
  Stream<BridgeEvent> crateApiHandshakeBridgeEventStream({required int seed});

  Future<void> crateApiMediaCancelTranscode({required int jobId});

  Future<String> crateApiMediaDefaultOutputPath({
    required String path,
    required MediaOutputMode mode,
  });

  Future<BackendCapabilitiesDto> crateApiMediaInitializeBackend();

  Future<void> crateApiHandshakeInitializeBridge();

  Stream<JobEventDto> crateApiMediaJobEvents();

  Future<BridgeHandshake> crateApiHandshakeNegotiateBridge({
    required BridgeHandshakeRequest request,
  });

  Future<MediaInfoDto> crateApiMediaProbeMedia({required String path});

  Future<JobSnapshotDto> crateApiMediaStartTranscode({
    required StartTranscodeRequestDto request,
  });
}

class MediaForgeRustLibApiImpl extends MediaForgeRustLibApiImplPlatform
    implements MediaForgeRustLibApi {
  MediaForgeRustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<BridgeEvent> crateApiHandshakeBridgeEventStream({required int seed}) {
    final sink = RustStreamSink<BridgeEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_CastedPrimitive_u_64(seed, serializer);
            sse_encode_StreamSink_bridge_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_bridge_error,
          ),
          constMeta: kCrateApiHandshakeBridgeEventStreamConstMeta,
          argValues: [seed, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiHandshakeBridgeEventStreamConstMeta =>
      const TaskConstMeta(
        debugName: 'bridge_event_stream',
        argNames: ['seed', 'sink'],
      );

  @override
  Future<void> crateApiMediaCancelTranscode({required int jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_u_64(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_media_bridge_error,
        ),
        constMeta: kCrateApiMediaCancelTranscodeConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaCancelTranscodeConstMeta =>
      const TaskConstMeta(debugName: 'cancel_transcode', argNames: ['jobId']);

  @override
  Future<String> crateApiMediaDefaultOutputPath({
    required String path,
    required MediaOutputMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_media_output_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_media_bridge_error,
        ),
        constMeta: kCrateApiMediaDefaultOutputPathConstMeta,
        argValues: [path, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaDefaultOutputPathConstMeta =>
      const TaskConstMeta(
        debugName: 'default_output_path',
        argNames: ['path', 'mode'],
      );

  @override
  Future<BackendCapabilitiesDto> crateApiMediaInitializeBackend() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_backend_capabilities_dto,
          decodeErrorData: sse_decode_media_bridge_error,
        ),
        constMeta: kCrateApiMediaInitializeBackendConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaInitializeBackendConstMeta =>
      const TaskConstMeta(debugName: 'initialize_backend', argNames: []);

  @override
  Future<void> crateApiHandshakeInitializeBridge() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHandshakeInitializeBridgeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHandshakeInitializeBridgeConstMeta =>
      const TaskConstMeta(debugName: 'initialize_bridge', argNames: []);

  @override
  Stream<JobEventDto> crateApiMediaJobEvents() {
    final sink = RustStreamSink<JobEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_job_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMediaJobEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMediaJobEventsConstMeta =>
      const TaskConstMeta(debugName: 'job_events', argNames: ['sink']);

  @override
  Future<BridgeHandshake> crateApiHandshakeNegotiateBridge({
    required BridgeHandshakeRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_bridge_handshake_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_handshake,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiHandshakeNegotiateBridgeConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHandshakeNegotiateBridgeConstMeta =>
      const TaskConstMeta(debugName: 'negotiate_bridge', argNames: ['request']);

  @override
  Future<MediaInfoDto> crateApiMediaProbeMedia({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_info_dto,
          decodeErrorData: sse_decode_media_bridge_error,
        ),
        constMeta: kCrateApiMediaProbeMediaConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaProbeMediaConstMeta =>
      const TaskConstMeta(debugName: 'probe_media', argNames: ['path']);

  @override
  Future<JobSnapshotDto> crateApiMediaStartTranscode({
    required StartTranscodeRequestDto request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_start_transcode_request_dto(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_job_snapshot_dto,
          decodeErrorData: sse_decode_media_bridge_error,
        ),
        constMeta: kCrateApiMediaStartTranscodeConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMediaStartTranscodeConstMeta =>
      const TaskConstMeta(debugName: 'start_transcode', argNames: ['request']);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  RustStreamSink<BridgeEvent> dco_decode_StreamSink_bridge_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<JobEventDto> dco_decode_StreamSink_job_event_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioStreamInfoDto dco_decode_audio_stream_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AudioStreamInfoDto(
      codec: dco_decode_String(arr[0]),
      sampleRate: dco_decode_opt_box_autoadd_u_32(arr[1]),
      channels: dco_decode_opt_box_autoadd_u_16(arr[2]),
      bitrate: dco_decode_opt_CastedPrimitive_u_64(arr[3]),
    );
  }

  @protected
  BackendCapabilitiesDto dco_decode_backend_capabilities_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BackendCapabilitiesDto(
      ffmpegVersion: dco_decode_String(arr[0]),
      h264Available: dco_decode_bool(arr[1]),
      aacAvailable: dco_decode_bool(arr[2]),
      mp3Available: dco_decode_bool(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AudioStreamInfoDto dco_decode_box_autoadd_audio_stream_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_audio_stream_info_dto(raw);
  }

  @protected
  BridgeHandshakeRequest dco_decode_box_autoadd_bridge_handshake_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_handshake_request(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  MediaBridgeError dco_decode_box_autoadd_media_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_bridge_error(raw);
  }

  @protected
  StartTranscodeRequestDto dco_decode_box_autoadd_start_transcode_request_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_start_transcode_request_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  VideoStreamInfoDto dco_decode_box_autoadd_video_stream_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_video_stream_info_dto(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeError(
      code: dco_decode_bridge_error_code(arr[0]),
      diagnostic: dco_decode_String(arr[1]),
    );
  }

  @protected
  BridgeErrorCode dco_decode_bridge_error_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeErrorCode.values[raw as int];
  }

  @protected
  BridgeEvent dco_decode_bridge_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BridgeEvent(
      kind: dco_decode_bridge_event_kind(arr[0]),
      protocolVersion: dco_decode_u_32(arr[1]),
      sequence: dco_decode_u_32(arr[2]),
      value: dco_decode_CastedPrimitive_u_64(arr[3]),
      sampleCount: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  BridgeEventKind dco_decode_bridge_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeEventKind.values[raw as int];
  }

  @protected
  BridgeHandshake dco_decode_bridge_handshake(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeHandshake(
      clientName: dco_decode_String(arr[0]),
      protocolVersion: dco_decode_u_32(arr[1]),
      bridgeVersion: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeHandshakeRequest dco_decode_bridge_handshake_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeHandshakeRequest(
      clientName: dco_decode_String(arr[0]),
      protocolVersion: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  JobEventDto dco_decode_job_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return JobEventDto(
      kind: dco_decode_job_event_kind_dto(arr[0]),
      jobId: dco_decode_CastedPrimitive_u_64(arr[1]),
      percent: dco_decode_opt_box_autoadd_f_64(arr[2]),
      processedMs: dco_decode_opt_CastedPrimitive_u_64(arr[3]),
      totalMs: dco_decode_opt_CastedPrimitive_u_64(arr[4]),
      framesPerSecond: dco_decode_opt_box_autoadd_f_64(arr[5]),
      speed: dco_decode_opt_box_autoadd_f_64(arr[6]),
      outputPath: dco_decode_opt_String(arr[7]),
      error: dco_decode_opt_box_autoadd_media_bridge_error(arr[8]),
    );
  }

  @protected
  JobEventKindDto dco_decode_job_event_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JobEventKindDto.values[raw as int];
  }

  @protected
  JobSnapshotDto dco_decode_job_snapshot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return JobSnapshotDto(
      jobId: dco_decode_CastedPrimitive_u_64(arr[0]),
      state: dco_decode_job_state_dto(arr[1]),
      inputPath: dco_decode_String(arr[2]),
      outputPath: dco_decode_String(arr[3]),
    );
  }

  @protected
  JobStateDto dco_decode_job_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JobStateDto.values[raw as int];
  }

  @protected
  List<MediaOutputMode> dco_decode_list_media_output_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_output_mode).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaAudioQuality dco_decode_media_audio_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaAudioQuality.values[raw as int];
  }

  @protected
  MediaBridgeError dco_decode_media_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MediaBridgeError(
      code: dco_decode_media_bridge_error_code(arr[0]),
      diagnostic: dco_decode_String(arr[1]),
    );
  }

  @protected
  MediaBridgeErrorCode dco_decode_media_bridge_error_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaBridgeErrorCode.values[raw as int];
  }

  @protected
  MediaInfoDto dco_decode_media_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MediaInfoDto(
      path: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      fileSizeBytes: dco_decode_CastedPrimitive_u_64(arr[2]),
      durationMs: dco_decode_CastedPrimitive_u_64(arr[3]),
      format: dco_decode_String(arr[4]),
      video: dco_decode_opt_box_autoadd_video_stream_info_dto(arr[5]),
      audio: dco_decode_opt_box_autoadd_audio_stream_info_dto(arr[6]),
      availableOutputModes: dco_decode_list_media_output_mode(arr[7]),
    );
  }

  @protected
  MediaOutputMode dco_decode_media_output_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaOutputMode.values[raw as int];
  }

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_CastedPrimitive_u_64(raw);
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AudioStreamInfoDto? dco_decode_opt_box_autoadd_audio_stream_info_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_audio_stream_info_dto(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  MediaBridgeError? dco_decode_opt_box_autoadd_media_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_media_bridge_error(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  VideoStreamInfoDto? dco_decode_opt_box_autoadd_video_stream_info_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_video_stream_info_dto(raw);
  }

  @protected
  StartTranscodeRequestDto dco_decode_start_transcode_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return StartTranscodeRequestDto(
      inputPath: dco_decode_String(arr[0]),
      outputPath: dco_decode_String(arr[1]),
      mode: dco_decode_media_output_mode(arr[2]),
      audioQuality: dco_decode_media_audio_quality(arr[3]),
      startMs: dco_decode_CastedPrimitive_u_64(arr[4]),
      endMs: dco_decode_CastedPrimitive_u_64(arr[5]),
      overwrite: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoStreamInfoDto dco_decode_video_stream_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VideoStreamInfoDto(
      codec: dco_decode_String(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      frameRate: dco_decode_opt_box_autoadd_f_64(arr[3]),
      bitrate: dco_decode_opt_CastedPrimitive_u_64(arr[4]),
      pixelFormat: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  RustStreamSink<BridgeEvent> sse_decode_StreamSink_bridge_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<JobEventDto> sse_decode_StreamSink_job_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioStreamInfoDto sse_decode_audio_stream_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_codec = sse_decode_String(deserializer);
    final var_sampleRate = sse_decode_opt_box_autoadd_u_32(deserializer);
    final var_channels = sse_decode_opt_box_autoadd_u_16(deserializer);
    final var_bitrate = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    return AudioStreamInfoDto(
      codec: var_codec,
      sampleRate: var_sampleRate,
      channels: var_channels,
      bitrate: var_bitrate,
    );
  }

  @protected
  BackendCapabilitiesDto sse_decode_backend_capabilities_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_ffmpegVersion = sse_decode_String(deserializer);
    final var_h264Available = sse_decode_bool(deserializer);
    final var_aacAvailable = sse_decode_bool(deserializer);
    final var_mp3Available = sse_decode_bool(deserializer);
    return BackendCapabilitiesDto(
      ffmpegVersion: var_ffmpegVersion,
      h264Available: var_h264Available,
      aacAvailable: var_aacAvailable,
      mp3Available: var_mp3Available,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AudioStreamInfoDto sse_decode_box_autoadd_audio_stream_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_audio_stream_info_dto(deserializer));
  }

  @protected
  BridgeHandshakeRequest sse_decode_box_autoadd_bridge_handshake_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_handshake_request(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  MediaBridgeError sse_decode_box_autoadd_media_bridge_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_bridge_error(deserializer));
  }

  @protected
  StartTranscodeRequestDto sse_decode_box_autoadd_start_transcode_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_start_transcode_request_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  VideoStreamInfoDto sse_decode_box_autoadd_video_stream_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_video_stream_info_dto(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_code = sse_decode_bridge_error_code(deserializer);
    final var_diagnostic = sse_decode_String(deserializer);
    return BridgeError(code: var_code, diagnostic: var_diagnostic);
  }

  @protected
  BridgeErrorCode sse_decode_bridge_error_code(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return BridgeErrorCode.values[inner];
  }

  @protected
  BridgeEvent sse_decode_bridge_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_kind = sse_decode_bridge_event_kind(deserializer);
    final var_protocolVersion = sse_decode_u_32(deserializer);
    final var_sequence = sse_decode_u_32(deserializer);
    final var_value = sse_decode_CastedPrimitive_u_64(deserializer);
    final var_sampleCount = sse_decode_u_32(deserializer);
    return BridgeEvent(
      kind: var_kind,
      protocolVersion: var_protocolVersion,
      sequence: var_sequence,
      value: var_value,
      sampleCount: var_sampleCount,
    );
  }

  @protected
  BridgeEventKind sse_decode_bridge_event_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return BridgeEventKind.values[inner];
  }

  @protected
  BridgeHandshake sse_decode_bridge_handshake(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_clientName = sse_decode_String(deserializer);
    final var_protocolVersion = sse_decode_u_32(deserializer);
    final var_bridgeVersion = sse_decode_String(deserializer);
    return BridgeHandshake(
      clientName: var_clientName,
      protocolVersion: var_protocolVersion,
      bridgeVersion: var_bridgeVersion,
    );
  }

  @protected
  BridgeHandshakeRequest sse_decode_bridge_handshake_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_clientName = sse_decode_String(deserializer);
    final var_protocolVersion = sse_decode_u_32(deserializer);
    return BridgeHandshakeRequest(
      clientName: var_clientName,
      protocolVersion: var_protocolVersion,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  JobEventDto sse_decode_job_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_kind = sse_decode_job_event_kind_dto(deserializer);
    final var_jobId = sse_decode_CastedPrimitive_u_64(deserializer);
    final var_percent = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_processedMs = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    final var_totalMs = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    final var_framesPerSecond = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_speed = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_outputPath = sse_decode_opt_String(deserializer);
    final var_error = sse_decode_opt_box_autoadd_media_bridge_error(
      deserializer,
    );
    return JobEventDto(
      kind: var_kind,
      jobId: var_jobId,
      percent: var_percent,
      processedMs: var_processedMs,
      totalMs: var_totalMs,
      framesPerSecond: var_framesPerSecond,
      speed: var_speed,
      outputPath: var_outputPath,
      error: var_error,
    );
  }

  @protected
  JobEventKindDto sse_decode_job_event_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return JobEventKindDto.values[inner];
  }

  @protected
  JobSnapshotDto sse_decode_job_snapshot_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_jobId = sse_decode_CastedPrimitive_u_64(deserializer);
    final var_state = sse_decode_job_state_dto(deserializer);
    final var_inputPath = sse_decode_String(deserializer);
    final var_outputPath = sse_decode_String(deserializer);
    return JobSnapshotDto(
      jobId: var_jobId,
      state: var_state,
      inputPath: var_inputPath,
      outputPath: var_outputPath,
    );
  }

  @protected
  JobStateDto sse_decode_job_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return JobStateDto.values[inner];
  }

  @protected
  List<MediaOutputMode> sse_decode_list_media_output_mode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <MediaOutputMode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_output_mode(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaAudioQuality sse_decode_media_audio_quality(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return MediaAudioQuality.values[inner];
  }

  @protected
  MediaBridgeError sse_decode_media_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_code = sse_decode_media_bridge_error_code(deserializer);
    final var_diagnostic = sse_decode_String(deserializer);
    return MediaBridgeError(code: var_code, diagnostic: var_diagnostic);
  }

  @protected
  MediaBridgeErrorCode sse_decode_media_bridge_error_code(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return MediaBridgeErrorCode.values[inner];
  }

  @protected
  MediaInfoDto sse_decode_media_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_path = sse_decode_String(deserializer);
    final var_fileName = sse_decode_String(deserializer);
    final var_fileSizeBytes = sse_decode_CastedPrimitive_u_64(deserializer);
    final var_durationMs = sse_decode_CastedPrimitive_u_64(deserializer);
    final var_format = sse_decode_String(deserializer);
    final var_video = sse_decode_opt_box_autoadd_video_stream_info_dto(
      deserializer,
    );
    final var_audio = sse_decode_opt_box_autoadd_audio_stream_info_dto(
      deserializer,
    );
    final var_availableOutputModes = sse_decode_list_media_output_mode(
      deserializer,
    );
    return MediaInfoDto(
      path: var_path,
      fileName: var_fileName,
      fileSizeBytes: var_fileSizeBytes,
      durationMs: var_durationMs,
      format: var_format,
      video: var_video,
      audio: var_audio,
      availableOutputModes: var_availableOutputModes,
    );
  }

  @protected
  MediaOutputMode sse_decode_media_output_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return MediaOutputMode.values[inner];
  }

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_CastedPrimitive_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AudioStreamInfoDto? sse_decode_opt_box_autoadd_audio_stream_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_audio_stream_info_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MediaBridgeError? sse_decode_opt_box_autoadd_media_bridge_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_media_bridge_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  VideoStreamInfoDto? sse_decode_opt_box_autoadd_video_stream_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_video_stream_info_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StartTranscodeRequestDto sse_decode_start_transcode_request_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_inputPath = sse_decode_String(deserializer);
    final var_outputPath = sse_decode_String(deserializer);
    final var_mode = sse_decode_media_output_mode(deserializer);
    final var_audioQuality = sse_decode_media_audio_quality(deserializer);
    final var_startMs = sse_decode_CastedPrimitive_u_64(deserializer);
    final var_endMs = sse_decode_CastedPrimitive_u_64(deserializer);
    final var_overwrite = sse_decode_bool(deserializer);
    return StartTranscodeRequestDto(
      inputPath: var_inputPath,
      outputPath: var_outputPath,
      mode: var_mode,
      audioQuality: var_audioQuality,
      startMs: var_startMs,
      endMs: var_endMs,
      overwrite: var_overwrite,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoStreamInfoDto sse_decode_video_stream_info_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_codec = sse_decode_String(deserializer);
    final var_width = sse_decode_u_32(deserializer);
    final var_height = sse_decode_u_32(deserializer);
    final var_frameRate = sse_decode_opt_box_autoadd_f_64(deserializer);
    final var_bitrate = sse_decode_opt_CastedPrimitive_u_64(deserializer);
    final var_pixelFormat = sse_decode_opt_String(deserializer);
    return VideoStreamInfoDto(
      codec: var_codec,
      width: var_width,
      height: var_height,
      frameRate: var_frameRate,
      bitrate: var_bitrate,
      pixelFormat: var_pixelFormat,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_StreamSink_bridge_event_Sse(
    RustStreamSink<BridgeEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_job_event_dto_Sse(
    RustStreamSink<JobEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_job_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_stream_info_dto(
    AudioStreamInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.codec, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sampleRate, serializer);
    sse_encode_opt_box_autoadd_u_16(self.channels, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.bitrate, serializer);
  }

  @protected
  void sse_encode_backend_capabilities_dto(
    BackendCapabilitiesDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ffmpegVersion, serializer);
    sse_encode_bool(self.h264Available, serializer);
    sse_encode_bool(self.aacAvailable, serializer);
    sse_encode_bool(self.mp3Available, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_audio_stream_info_dto(
    AudioStreamInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_audio_stream_info_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_handshake_request(
    BridgeHandshakeRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_handshake_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_media_bridge_error(
    MediaBridgeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_bridge_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_start_transcode_request_dto(
    StartTranscodeRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_start_transcode_request_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_video_stream_info_dto(
    VideoStreamInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_stream_info_dto(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_error_code(self.code, serializer);
    sse_encode_String(self.diagnostic, serializer);
  }

  @protected
  void sse_encode_bridge_error_code(
    BridgeErrorCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_event(BridgeEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_event_kind(self.kind, serializer);
    sse_encode_u_32(self.protocolVersion, serializer);
    sse_encode_u_32(self.sequence, serializer);
    sse_encode_CastedPrimitive_u_64(self.value, serializer);
    sse_encode_u_32(self.sampleCount, serializer);
  }

  @protected
  void sse_encode_bridge_event_kind(
    BridgeEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_handshake(
    BridgeHandshake self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.clientName, serializer);
    sse_encode_u_32(self.protocolVersion, serializer);
    sse_encode_String(self.bridgeVersion, serializer);
  }

  @protected
  void sse_encode_bridge_handshake_request(
    BridgeHandshakeRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.clientName, serializer);
    sse_encode_u_32(self.protocolVersion, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_job_event_dto(JobEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_job_event_kind_dto(self.kind, serializer);
    sse_encode_CastedPrimitive_u_64(self.jobId, serializer);
    sse_encode_opt_box_autoadd_f_64(self.percent, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.processedMs, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.totalMs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.framesPerSecond, serializer);
    sse_encode_opt_box_autoadd_f_64(self.speed, serializer);
    sse_encode_opt_String(self.outputPath, serializer);
    sse_encode_opt_box_autoadd_media_bridge_error(self.error, serializer);
  }

  @protected
  void sse_encode_job_event_kind_dto(
    JobEventKindDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_job_snapshot_dto(
    JobSnapshotDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.jobId, serializer);
    sse_encode_job_state_dto(self.state, serializer);
    sse_encode_String(self.inputPath, serializer);
    sse_encode_String(self.outputPath, serializer);
  }

  @protected
  void sse_encode_job_state_dto(JobStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_media_output_mode(
    List<MediaOutputMode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_output_mode(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_audio_quality(
    MediaAudioQuality self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_media_bridge_error(
    MediaBridgeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_bridge_error_code(self.code, serializer);
    sse_encode_String(self.diagnostic, serializer);
  }

  @protected
  void sse_encode_media_bridge_error_code(
    MediaBridgeErrorCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_media_info_dto(MediaInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_CastedPrimitive_u_64(self.fileSizeBytes, serializer);
    sse_encode_CastedPrimitive_u_64(self.durationMs, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_opt_box_autoadd_video_stream_info_dto(self.video, serializer);
    sse_encode_opt_box_autoadd_audio_stream_info_dto(self.audio, serializer);
    sse_encode_list_media_output_mode(self.availableOutputModes, serializer);
  }

  @protected
  void sse_encode_media_output_mode(
    MediaOutputMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(
    int? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_CastedPrimitive_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_audio_stream_info_dto(
    AudioStreamInfoDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_audio_stream_info_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_media_bridge_error(
    MediaBridgeError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_media_bridge_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_video_stream_info_dto(
    VideoStreamInfoDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_video_stream_info_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_start_transcode_request_dto(
    StartTranscodeRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.inputPath, serializer);
    sse_encode_String(self.outputPath, serializer);
    sse_encode_media_output_mode(self.mode, serializer);
    sse_encode_media_audio_quality(self.audioQuality, serializer);
    sse_encode_CastedPrimitive_u_64(self.startMs, serializer);
    sse_encode_CastedPrimitive_u_64(self.endMs, serializer);
    sse_encode_bool(self.overwrite, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_stream_info_dto(
    VideoStreamInfoDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.codec, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_opt_box_autoadd_f_64(self.frameRate, serializer);
    sse_encode_opt_CastedPrimitive_u_64(self.bitrate, serializer);
    sse_encode_opt_String(self.pixelFormat, serializer);
  }
}
