// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 688988532;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__handshake__bridge_event_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "bridge_event_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_seed = <u64>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::handshake::BridgeEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::handshake::BridgeError>((move || {
                    let output_ok = crate::api::handshake::bridge_event_stream(api_seed, api_sink)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__media__cancel_transcode_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "cancel_transcode",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_job_id = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::media::MediaBridgeError>((move || {
                    let output_ok = crate::api::media::cancel_transcode(api_job_id)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__media__default_output_path_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "default_output_path",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_mode = <crate::api::media::MediaOutputMode>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::media::MediaBridgeError>((move || {
                    let output_ok = crate::api::media::default_output_path(api_path, api_mode)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__media__initialize_backend_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize_backend",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::media::MediaBridgeError>((move || {
                    let output_ok = crate::api::media::initialize_backend()?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__handshake__initialize_bridge_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize_bridge",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::handshake::initialize_bridge();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__media__job_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "job_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::media::JobEventDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::media::job_events(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__handshake__negotiate_bridge_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "negotiate_bridge",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::handshake::BridgeHandshakeRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::handshake::BridgeError>((move || {
                    let output_ok = crate::api::handshake::negotiate_bridge(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__media__probe_media_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "probe_media",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::media::MediaBridgeError>((move || {
                    let output_ok = crate::api::media::probe_media(api_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__media__start_transcode_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_transcode",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::media::StartTranscodeRequestDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::media::MediaBridgeError>((move || {
                    let output_ok = crate::api::media::start_transcode(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::handshake::BridgeEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::media::JobEventDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::media::AudioStreamInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_codec = <String>::sse_decode(deserializer);
        let mut var_sampleRate = <Option<u32>>::sse_decode(deserializer);
        let mut var_channels = <Option<u16>>::sse_decode(deserializer);
        let mut var_bitrate = <Option<u64>>::sse_decode(deserializer);
        return crate::api::media::AudioStreamInfoDto {
            codec: var_codec,
            sample_rate: var_sampleRate,
            channels: var_channels,
            bitrate: var_bitrate,
        };
    }
}

impl SseDecode for crate::api::media::BackendCapabilitiesDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ffmpegVersion = <String>::sse_decode(deserializer);
        let mut var_h264Available = <bool>::sse_decode(deserializer);
        let mut var_aacAvailable = <bool>::sse_decode(deserializer);
        let mut var_mp3Available = <bool>::sse_decode(deserializer);
        return crate::api::media::BackendCapabilitiesDto {
            ffmpeg_version: var_ffmpegVersion,
            h264_available: var_h264Available,
            aac_available: var_aacAvailable,
            mp3_available: var_mp3Available,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::handshake::BridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <crate::api::handshake::BridgeErrorCode>::sse_decode(deserializer);
        let mut var_diagnostic = <String>::sse_decode(deserializer);
        return crate::api::handshake::BridgeError {
            code: var_code,
            diagnostic: var_diagnostic,
        };
    }
}

impl SseDecode for crate::api::handshake::BridgeErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::handshake::BridgeErrorCode::InvalidClientName,
            1 => crate::api::handshake::BridgeErrorCode::UnsupportedProtocol,
            2 => crate::api::handshake::BridgeErrorCode::EventDeliveryFailed,
            _ => unreachable!("Invalid variant for BridgeErrorCode: {}", inner),
        };
    }
}

impl SseDecode for crate::api::handshake::BridgeEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::handshake::BridgeEventKind>::sse_decode(deserializer);
        let mut var_protocolVersion = <u32>::sse_decode(deserializer);
        let mut var_sequence = <u32>::sse_decode(deserializer);
        let mut var_value = <u64>::sse_decode(deserializer);
        let mut var_sampleCount = <u32>::sse_decode(deserializer);
        return crate::api::handshake::BridgeEvent {
            kind: var_kind,
            protocol_version: var_protocolVersion,
            sequence: var_sequence,
            value: var_value,
            sample_count: var_sampleCount,
        };
    }
}

impl SseDecode for crate::api::handshake::BridgeEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::handshake::BridgeEventKind::Ready,
            1 => crate::api::handshake::BridgeEventKind::Sample,
            2 => crate::api::handshake::BridgeEventKind::Finished,
            _ => unreachable!("Invalid variant for BridgeEventKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::handshake::BridgeHandshake {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_clientName = <String>::sse_decode(deserializer);
        let mut var_protocolVersion = <u32>::sse_decode(deserializer);
        let mut var_bridgeVersion = <String>::sse_decode(deserializer);
        return crate::api::handshake::BridgeHandshake {
            client_name: var_clientName,
            protocol_version: var_protocolVersion,
            bridge_version: var_bridgeVersion,
        };
    }
}

impl SseDecode for crate::api::handshake::BridgeHandshakeRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_clientName = <String>::sse_decode(deserializer);
        let mut var_protocolVersion = <u32>::sse_decode(deserializer);
        return crate::api::handshake::BridgeHandshakeRequest {
            client_name: var_clientName,
            protocol_version: var_protocolVersion,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::media::JobEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::media::JobEventKindDto>::sse_decode(deserializer);
        let mut var_jobId = <u64>::sse_decode(deserializer);
        let mut var_percent = <Option<f64>>::sse_decode(deserializer);
        let mut var_processedMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_totalMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_framesPerSecond = <Option<f64>>::sse_decode(deserializer);
        let mut var_speed = <Option<f64>>::sse_decode(deserializer);
        let mut var_outputPath = <Option<String>>::sse_decode(deserializer);
        let mut var_error = <Option<crate::api::media::MediaBridgeError>>::sse_decode(deserializer);
        return crate::api::media::JobEventDto {
            kind: var_kind,
            job_id: var_jobId,
            percent: var_percent,
            processed_ms: var_processedMs,
            total_ms: var_totalMs,
            frames_per_second: var_framesPerSecond,
            speed: var_speed,
            output_path: var_outputPath,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::media::JobEventKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::media::JobEventKindDto::Preparing,
            1 => crate::api::media::JobEventKindDto::Progress,
            2 => crate::api::media::JobEventKindDto::Completed,
            3 => crate::api::media::JobEventKindDto::Cancelled,
            4 => crate::api::media::JobEventKindDto::Failed,
            _ => unreachable!("Invalid variant for JobEventKindDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::media::JobSnapshotDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_jobId = <u64>::sse_decode(deserializer);
        let mut var_state = <crate::api::media::JobStateDto>::sse_decode(deserializer);
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <String>::sse_decode(deserializer);
        return crate::api::media::JobSnapshotDto {
            job_id: var_jobId,
            state: var_state,
            input_path: var_inputPath,
            output_path: var_outputPath,
        };
    }
}

impl SseDecode for crate::api::media::JobStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::media::JobStateDto::Idle,
            1 => crate::api::media::JobStateDto::Preparing,
            2 => crate::api::media::JobStateDto::Running,
            3 => crate::api::media::JobStateDto::Completed,
            4 => crate::api::media::JobStateDto::Cancelled,
            5 => crate::api::media::JobStateDto::Failed,
            _ => unreachable!("Invalid variant for JobStateDto: {}", inner),
        };
    }
}

impl SseDecode for Vec<crate::api::media::MediaOutputMode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::media::MediaOutputMode>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::media::MediaAudioQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::media::MediaAudioQuality::High,
            1 => crate::api::media::MediaAudioQuality::Medium,
            2 => crate::api::media::MediaAudioQuality::Low,
            _ => unreachable!("Invalid variant for MediaAudioQuality: {}", inner),
        };
    }
}

impl SseDecode for crate::api::media::MediaBridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <crate::api::media::MediaBridgeErrorCode>::sse_decode(deserializer);
        let mut var_diagnostic = <String>::sse_decode(deserializer);
        return crate::api::media::MediaBridgeError {
            code: var_code,
            diagnostic: var_diagnostic,
        };
    }
}

impl SseDecode for crate::api::media::MediaBridgeErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::media::MediaBridgeErrorCode::UnsupportedInput,
            1 => crate::api::media::MediaBridgeErrorCode::CannotOpenInput,
            2 => crate::api::media::MediaBridgeErrorCode::DecodeFailed,
            3 => crate::api::media::MediaBridgeErrorCode::EncoderUnavailable,
            4 => crate::api::media::MediaBridgeErrorCode::InvalidTrimRange,
            5 => crate::api::media::MediaBridgeErrorCode::OutputExists,
            6 => crate::api::media::MediaBridgeErrorCode::OutputCreateFailed,
            7 => crate::api::media::MediaBridgeErrorCode::DiskWriteFailed,
            8 => crate::api::media::MediaBridgeErrorCode::JobActive,
            9 => crate::api::media::MediaBridgeErrorCode::JobNotFound,
            10 => crate::api::media::MediaBridgeErrorCode::Cancelled,
            11 => crate::api::media::MediaBridgeErrorCode::Unexpected,
            _ => unreachable!("Invalid variant for MediaBridgeErrorCode: {}", inner),
        };
    }
}

impl SseDecode for crate::api::media::MediaInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_path = <String>::sse_decode(deserializer);
        let mut var_fileName = <String>::sse_decode(deserializer);
        let mut var_fileSizeBytes = <u64>::sse_decode(deserializer);
        let mut var_durationMs = <u64>::sse_decode(deserializer);
        let mut var_format = <String>::sse_decode(deserializer);
        let mut var_video =
            <Option<crate::api::media::VideoStreamInfoDto>>::sse_decode(deserializer);
        let mut var_audio =
            <Option<crate::api::media::AudioStreamInfoDto>>::sse_decode(deserializer);
        let mut var_availableOutputModes =
            <Vec<crate::api::media::MediaOutputMode>>::sse_decode(deserializer);
        return crate::api::media::MediaInfoDto {
            path: var_path,
            file_name: var_fileName,
            file_size_bytes: var_fileSizeBytes,
            duration_ms: var_durationMs,
            format: var_format,
            video: var_video,
            audio: var_audio,
            available_output_modes: var_availableOutputModes,
        };
    }
}

impl SseDecode for crate::api::media::MediaOutputMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::media::MediaOutputMode::VideoWithAudio,
            1 => crate::api::media::MediaOutputMode::VideoOnly,
            2 => crate::api::media::MediaOutputMode::AudioOnly,
            _ => unreachable!("Invalid variant for MediaOutputMode: {}", inner),
        };
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::media::AudioStreamInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::media::AudioStreamInfoDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::media::MediaBridgeError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::media::MediaBridgeError>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u16>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::media::VideoStreamInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::media::VideoStreamInfoDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::media::StartTranscodeRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_inputPath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_mode = <crate::api::media::MediaOutputMode>::sse_decode(deserializer);
        let mut var_audioQuality = <crate::api::media::MediaAudioQuality>::sse_decode(deserializer);
        let mut var_startMs = <u64>::sse_decode(deserializer);
        let mut var_endMs = <u64>::sse_decode(deserializer);
        let mut var_overwrite = <bool>::sse_decode(deserializer);
        return crate::api::media::StartTranscodeRequestDto {
            input_path: var_inputPath,
            output_path: var_outputPath,
            mode: var_mode,
            audio_quality: var_audioQuality,
            start_ms: var_startMs,
            end_ms: var_endMs,
            overwrite: var_overwrite,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::media::VideoStreamInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_codec = <String>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_frameRate = <Option<f64>>::sse_decode(deserializer);
        let mut var_bitrate = <Option<u64>>::sse_decode(deserializer);
        let mut var_pixelFormat = <Option<String>>::sse_decode(deserializer);
        return crate::api::media::VideoStreamInfoDto {
            codec: var_codec,
            width: var_width,
            height: var_height,
            frame_rate: var_frameRate,
            bitrate: var_bitrate,
            pixel_format: var_pixelFormat,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => {
            wire__crate__api__handshake__bridge_event_stream_impl(port, ptr, rust_vec_len, data_len)
        }
        2 => wire__crate__api__media__cancel_transcode_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__media__default_output_path_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__media__initialize_backend_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__handshake__initialize_bridge_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__media__job_events_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__handshake__negotiate_bridge_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__media__probe_media_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__media__start_transcode_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::AudioStreamInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.codec.into_into_dart().into_dart(),
            self.sample_rate.into_into_dart().into_dart(),
            self.channels.into_into_dart().into_dart(),
            self.bitrate.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::AudioStreamInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::AudioStreamInfoDto>
    for crate::api::media::AudioStreamInfoDto
{
    fn into_into_dart(self) -> crate::api::media::AudioStreamInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::BackendCapabilitiesDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ffmpeg_version.into_into_dart().into_dart(),
            self.h264_available.into_into_dart().into_dart(),
            self.aac_available.into_into_dart().into_dart(),
            self.mp3_available.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::BackendCapabilitiesDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::BackendCapabilitiesDto>
    for crate::api::media::BackendCapabilitiesDto
{
    fn into_into_dart(self) -> crate::api::media::BackendCapabilitiesDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::handshake::BridgeError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.diagnostic.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::handshake::BridgeError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::handshake::BridgeError>
    for crate::api::handshake::BridgeError
{
    fn into_into_dart(self) -> crate::api::handshake::BridgeError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::handshake::BridgeErrorCode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidClientName => 0.into_dart(),
            Self::UnsupportedProtocol => 1.into_dart(),
            Self::EventDeliveryFailed => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::handshake::BridgeErrorCode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::handshake::BridgeErrorCode>
    for crate::api::handshake::BridgeErrorCode
{
    fn into_into_dart(self) -> crate::api::handshake::BridgeErrorCode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::handshake::BridgeEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.protocol_version.into_into_dart().into_dart(),
            self.sequence.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.sample_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::handshake::BridgeEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::handshake::BridgeEvent>
    for crate::api::handshake::BridgeEvent
{
    fn into_into_dart(self) -> crate::api::handshake::BridgeEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::handshake::BridgeEventKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Ready => 0.into_dart(),
            Self::Sample => 1.into_dart(),
            Self::Finished => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::handshake::BridgeEventKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::handshake::BridgeEventKind>
    for crate::api::handshake::BridgeEventKind
{
    fn into_into_dart(self) -> crate::api::handshake::BridgeEventKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::handshake::BridgeHandshake {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.client_name.into_into_dart().into_dart(),
            self.protocol_version.into_into_dart().into_dart(),
            self.bridge_version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::handshake::BridgeHandshake
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::handshake::BridgeHandshake>
    for crate::api::handshake::BridgeHandshake
{
    fn into_into_dart(self) -> crate::api::handshake::BridgeHandshake {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::handshake::BridgeHandshakeRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.client_name.into_into_dart().into_dart(),
            self.protocol_version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::handshake::BridgeHandshakeRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::handshake::BridgeHandshakeRequest>
    for crate::api::handshake::BridgeHandshakeRequest
{
    fn into_into_dart(self) -> crate::api::handshake::BridgeHandshakeRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::JobEventDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.job_id.into_into_dart().into_dart(),
            self.percent.into_into_dart().into_dart(),
            self.processed_ms.into_into_dart().into_dart(),
            self.total_ms.into_into_dart().into_dart(),
            self.frames_per_second.into_into_dart().into_dart(),
            self.speed.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::JobEventDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::JobEventDto>
    for crate::api::media::JobEventDto
{
    fn into_into_dart(self) -> crate::api::media::JobEventDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::JobEventKindDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Preparing => 0.into_dart(),
            Self::Progress => 1.into_dart(),
            Self::Completed => 2.into_dart(),
            Self::Cancelled => 3.into_dart(),
            Self::Failed => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::JobEventKindDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::JobEventKindDto>
    for crate::api::media::JobEventKindDto
{
    fn into_into_dart(self) -> crate::api::media::JobEventKindDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::JobSnapshotDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.job_id.into_into_dart().into_dart(),
            self.state.into_into_dart().into_dart(),
            self.input_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::JobSnapshotDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::JobSnapshotDto>
    for crate::api::media::JobSnapshotDto
{
    fn into_into_dart(self) -> crate::api::media::JobSnapshotDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::JobStateDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Idle => 0.into_dart(),
            Self::Preparing => 1.into_dart(),
            Self::Running => 2.into_dart(),
            Self::Completed => 3.into_dart(),
            Self::Cancelled => 4.into_dart(),
            Self::Failed => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::JobStateDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::JobStateDto>
    for crate::api::media::JobStateDto
{
    fn into_into_dart(self) -> crate::api::media::JobStateDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::MediaAudioQuality {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::High => 0.into_dart(),
            Self::Medium => 1.into_dart(),
            Self::Low => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::MediaAudioQuality
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::MediaAudioQuality>
    for crate::api::media::MediaAudioQuality
{
    fn into_into_dart(self) -> crate::api::media::MediaAudioQuality {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::MediaBridgeError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.diagnostic.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::MediaBridgeError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::MediaBridgeError>
    for crate::api::media::MediaBridgeError
{
    fn into_into_dart(self) -> crate::api::media::MediaBridgeError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::MediaBridgeErrorCode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::UnsupportedInput => 0.into_dart(),
            Self::CannotOpenInput => 1.into_dart(),
            Self::DecodeFailed => 2.into_dart(),
            Self::EncoderUnavailable => 3.into_dart(),
            Self::InvalidTrimRange => 4.into_dart(),
            Self::OutputExists => 5.into_dart(),
            Self::OutputCreateFailed => 6.into_dart(),
            Self::DiskWriteFailed => 7.into_dart(),
            Self::JobActive => 8.into_dart(),
            Self::JobNotFound => 9.into_dart(),
            Self::Cancelled => 10.into_dart(),
            Self::Unexpected => 11.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::MediaBridgeErrorCode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::MediaBridgeErrorCode>
    for crate::api::media::MediaBridgeErrorCode
{
    fn into_into_dart(self) -> crate::api::media::MediaBridgeErrorCode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::MediaInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.path.into_into_dart().into_dart(),
            self.file_name.into_into_dart().into_dart(),
            self.file_size_bytes.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.video.into_into_dart().into_dart(),
            self.audio.into_into_dart().into_dart(),
            self.available_output_modes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::MediaInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::MediaInfoDto>
    for crate::api::media::MediaInfoDto
{
    fn into_into_dart(self) -> crate::api::media::MediaInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::MediaOutputMode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::VideoWithAudio => 0.into_dart(),
            Self::VideoOnly => 1.into_dart(),
            Self::AudioOnly => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::MediaOutputMode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::MediaOutputMode>
    for crate::api::media::MediaOutputMode
{
    fn into_into_dart(self) -> crate::api::media::MediaOutputMode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::StartTranscodeRequestDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.input_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.mode.into_into_dart().into_dart(),
            self.audio_quality.into_into_dart().into_dart(),
            self.start_ms.into_into_dart().into_dart(),
            self.end_ms.into_into_dart().into_dart(),
            self.overwrite.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::StartTranscodeRequestDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::StartTranscodeRequestDto>
    for crate::api::media::StartTranscodeRequestDto
{
    fn into_into_dart(self) -> crate::api::media::StartTranscodeRequestDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::VideoStreamInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.codec.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.frame_rate.into_into_dart().into_dart(),
            self.bitrate.into_into_dart().into_dart(),
            self.pixel_format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::VideoStreamInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::VideoStreamInfoDto>
    for crate::api::media::VideoStreamInfoDto
{
    fn into_into_dart(self) -> crate::api::media::VideoStreamInfoDto {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::handshake::BridgeEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<crate::api::media::JobEventDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::media::AudioStreamInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.codec, serializer);
        <Option<u32>>::sse_encode(self.sample_rate, serializer);
        <Option<u16>>::sse_encode(self.channels, serializer);
        <Option<u64>>::sse_encode(self.bitrate, serializer);
    }
}

impl SseEncode for crate::api::media::BackendCapabilitiesDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.ffmpeg_version, serializer);
        <bool>::sse_encode(self.h264_available, serializer);
        <bool>::sse_encode(self.aac_available, serializer);
        <bool>::sse_encode(self.mp3_available, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::handshake::BridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::handshake::BridgeErrorCode>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.diagnostic, serializer);
    }
}

impl SseEncode for crate::api::handshake::BridgeErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::handshake::BridgeErrorCode::InvalidClientName => 0,
                crate::api::handshake::BridgeErrorCode::UnsupportedProtocol => 1,
                crate::api::handshake::BridgeErrorCode::EventDeliveryFailed => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::handshake::BridgeEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::handshake::BridgeEventKind>::sse_encode(self.kind, serializer);
        <u32>::sse_encode(self.protocol_version, serializer);
        <u32>::sse_encode(self.sequence, serializer);
        <u64>::sse_encode(self.value, serializer);
        <u32>::sse_encode(self.sample_count, serializer);
    }
}

impl SseEncode for crate::api::handshake::BridgeEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::handshake::BridgeEventKind::Ready => 0,
                crate::api::handshake::BridgeEventKind::Sample => 1,
                crate::api::handshake::BridgeEventKind::Finished => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::handshake::BridgeHandshake {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.client_name, serializer);
        <u32>::sse_encode(self.protocol_version, serializer);
        <String>::sse_encode(self.bridge_version, serializer);
    }
}

impl SseEncode for crate::api::handshake::BridgeHandshakeRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.client_name, serializer);
        <u32>::sse_encode(self.protocol_version, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::media::JobEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::media::JobEventKindDto>::sse_encode(self.kind, serializer);
        <u64>::sse_encode(self.job_id, serializer);
        <Option<f64>>::sse_encode(self.percent, serializer);
        <Option<u64>>::sse_encode(self.processed_ms, serializer);
        <Option<u64>>::sse_encode(self.total_ms, serializer);
        <Option<f64>>::sse_encode(self.frames_per_second, serializer);
        <Option<f64>>::sse_encode(self.speed, serializer);
        <Option<String>>::sse_encode(self.output_path, serializer);
        <Option<crate::api::media::MediaBridgeError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::media::JobEventKindDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::media::JobEventKindDto::Preparing => 0,
                crate::api::media::JobEventKindDto::Progress => 1,
                crate::api::media::JobEventKindDto::Completed => 2,
                crate::api::media::JobEventKindDto::Cancelled => 3,
                crate::api::media::JobEventKindDto::Failed => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::media::JobSnapshotDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.job_id, serializer);
        <crate::api::media::JobStateDto>::sse_encode(self.state, serializer);
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.output_path, serializer);
    }
}

impl SseEncode for crate::api::media::JobStateDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::media::JobStateDto::Idle => 0,
                crate::api::media::JobStateDto::Preparing => 1,
                crate::api::media::JobStateDto::Running => 2,
                crate::api::media::JobStateDto::Completed => 3,
                crate::api::media::JobStateDto::Cancelled => 4,
                crate::api::media::JobStateDto::Failed => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for Vec<crate::api::media::MediaOutputMode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::media::MediaOutputMode>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::media::MediaAudioQuality {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::media::MediaAudioQuality::High => 0,
                crate::api::media::MediaAudioQuality::Medium => 1,
                crate::api::media::MediaAudioQuality::Low => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::media::MediaBridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::media::MediaBridgeErrorCode>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.diagnostic, serializer);
    }
}

impl SseEncode for crate::api::media::MediaBridgeErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::media::MediaBridgeErrorCode::UnsupportedInput => 0,
                crate::api::media::MediaBridgeErrorCode::CannotOpenInput => 1,
                crate::api::media::MediaBridgeErrorCode::DecodeFailed => 2,
                crate::api::media::MediaBridgeErrorCode::EncoderUnavailable => 3,
                crate::api::media::MediaBridgeErrorCode::InvalidTrimRange => 4,
                crate::api::media::MediaBridgeErrorCode::OutputExists => 5,
                crate::api::media::MediaBridgeErrorCode::OutputCreateFailed => 6,
                crate::api::media::MediaBridgeErrorCode::DiskWriteFailed => 7,
                crate::api::media::MediaBridgeErrorCode::JobActive => 8,
                crate::api::media::MediaBridgeErrorCode::JobNotFound => 9,
                crate::api::media::MediaBridgeErrorCode::Cancelled => 10,
                crate::api::media::MediaBridgeErrorCode::Unexpected => 11,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::media::MediaInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.path, serializer);
        <String>::sse_encode(self.file_name, serializer);
        <u64>::sse_encode(self.file_size_bytes, serializer);
        <u64>::sse_encode(self.duration_ms, serializer);
        <String>::sse_encode(self.format, serializer);
        <Option<crate::api::media::VideoStreamInfoDto>>::sse_encode(self.video, serializer);
        <Option<crate::api::media::AudioStreamInfoDto>>::sse_encode(self.audio, serializer);
        <Vec<crate::api::media::MediaOutputMode>>::sse_encode(
            self.available_output_modes,
            serializer,
        );
    }
}

impl SseEncode for crate::api::media::MediaOutputMode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::media::MediaOutputMode::VideoWithAudio => 0,
                crate::api::media::MediaOutputMode::VideoOnly => 1,
                crate::api::media::MediaOutputMode::AudioOnly => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::media::AudioStreamInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::media::AudioStreamInfoDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::media::MediaBridgeError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::media::MediaBridgeError>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u16> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u16>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::media::VideoStreamInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::media::VideoStreamInfoDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::media::StartTranscodeRequestDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.input_path, serializer);
        <String>::sse_encode(self.output_path, serializer);
        <crate::api::media::MediaOutputMode>::sse_encode(self.mode, serializer);
        <crate::api::media::MediaAudioQuality>::sse_encode(self.audio_quality, serializer);
        <u64>::sse_encode(self.start_ms, serializer);
        <u64>::sse_encode(self.end_ms, serializer);
        <bool>::sse_encode(self.overwrite, serializer);
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::media::VideoStreamInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.codec, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <Option<f64>>::sse_encode(self.frame_rate, serializer);
        <Option<u64>>::sse_encode(self.bitrate, serializer);
        <Option<String>>::sse_encode(self.pixel_format, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
