// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bridge_events`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Validates the presentation process and returns the native bridge identity.
///
/// # Errors
///
/// Returns [`BridgeErrorCode::InvalidClientName`] for a blank client label or
/// [`BridgeErrorCode::UnsupportedProtocol`] when the protocol does not match.
Future<BridgeHandshake> negotiateBridge({
  required BridgeHandshakeRequest request,
}) => MediaForgeRustLib.instance.api.crateApiHandshakeNegotiateBridge(
  request: request,
);

/// Emits a finite ordered sequence and closes after the terminal event.
///
/// # Errors
///
/// Returns [`BridgeErrorCode::EventDeliveryFailed`] if Dart closes the stream
/// before Rust delivers the complete sequence.
Stream<BridgeEvent> bridgeEventStream({required int seed}) => MediaForgeRustLib
    .instance
    .api
    .crateApiHandshakeBridgeEventStream(seed: seed);

/// Structured failure crossing the generated FRB boundary.
class BridgeError implements FrbException {
  const BridgeError({required this.code, required this.diagnostic});

  /// Stable category used by presentation control flow.
  final BridgeErrorCode code;

  /// Diagnostic cause retained for structured development logs.
  final String diagnostic;

  @override
  int get hashCode => code.hashCode ^ diagnostic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          diagnostic == other.diagnostic;
}

/// Stable categories for bridge-boundary failures.
enum BridgeErrorCode {
  /// The presentation process did not provide an identity.
  invalidClientName,

  /// The presentation and native bridge protocols do not match.
  unsupportedProtocol,

  /// A Rust-to-Dart event could not be delivered.
  eventDeliveryFailed,
}

/// Deterministic event proving ordered Rust-to-Dart stream delivery.
class BridgeEvent {
  const BridgeEvent({
    required this.kind,
    required this.protocolVersion,
    required this.sequence,
    required this.value,
    required this.sampleCount,
  });

  /// Discriminator controlling which payload field is meaningful.
  final BridgeEventKind kind;

  /// Negotiated version for `Ready`, otherwise zero.
  final int protocolVersion;

  /// Sample position for `Sample`, otherwise zero.
  final int sequence;

  /// Caller seed plus sample position for `Sample`, otherwise zero.
  final int value;

  /// Emitted sample total for `Finished`, otherwise zero.
  final int sampleCount;

  @override
  int get hashCode =>
      kind.hashCode ^
      protocolVersion.hashCode ^
      sequence.hashCode ^
      value.hashCode ^
      sampleCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          protocolVersion == other.protocolVersion &&
          sequence == other.sequence &&
          value == other.value &&
          sampleCount == other.sampleCount;
}

/// Kinds emitted by the deterministic bridge event stream.
enum BridgeEventKind {
  /// The stream accepted a protocol and will emit samples.
  ready,

  /// One ordered bridge sample.
  sample,

  /// The stream emitted every promised sample.
  finished,
}

/// Successful bridge negotiation returned to the presentation process.
class BridgeHandshake {
  const BridgeHandshake({
    required this.clientName,
    required this.protocolVersion,
    required this.bridgeVersion,
  });

  /// Client label accepted by the Rust adapter.
  final String clientName;

  /// Protocol version accepted by both sides.
  final int protocolVersion;

  /// Rust package version used to build the loaded native library.
  final String bridgeVersion;

  @override
  int get hashCode =>
      clientName.hashCode ^ protocolVersion.hashCode ^ bridgeVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHandshake &&
          runtimeType == other.runtimeType &&
          clientName == other.clientName &&
          protocolVersion == other.protocolVersion &&
          bridgeVersion == other.bridgeVersion;
}

/// Request sent by a presentation process when validating bridge connectivity.
class BridgeHandshakeRequest {
  const BridgeHandshakeRequest({
    required this.clientName,
    required this.protocolVersion,
  });

  /// Non-empty presentation process label retained for diagnostics.
  final String clientName;

  /// Protocol version understood by the presentation process.
  final int protocolVersion;

  @override
  int get hashCode => clientName.hashCode ^ protocolVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHandshakeRequest &&
          runtimeType == other.runtimeType &&
          clientName == other.clientName &&
          protocolVersion == other.protocolVersion;
}
