// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `canonicalize_path`, `media_facade`, `path_to_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`

/// Initializes the process-wide `FFmpeg` adapter and reports its capabilities.
///
/// # Errors
///
/// Returns a structured failure when the repository-built `FFmpeg` libraries
/// cannot initialize.
Future<BackendCapabilitiesDto> initializeBackend() =>
    MediaForgeRustLib.instance.api.crateApiMediaInitializeBackend();

/// Canonicalizes and probes one regular local media file on FRB's Rust executor.
///
/// # Errors
///
/// Returns a structured application failure when the path cannot be
/// canonicalized, the input is unsupported, or `FFmpeg` cannot inspect it.
Future<MediaInfoDto> probeMedia({required String path}) =>
    MediaForgeRustLib.instance.api.crateApiMediaProbeMedia(path: path);

/// Proposes a destination beside a canonical source for one supported recipe.
///
/// # Errors
///
/// Returns a structured path failure when the source cannot be canonicalized or
/// the resulting destination cannot be represented losslessly for Dart.
Future<String> defaultOutputPath({
  required String path,
  required MediaOutputMode mode,
}) => MediaForgeRustLib.instance.api.crateApiMediaDefaultOutputPath(
  path: path,
  mode: mode,
);

/// Primary audio metadata safe to expose through FRB.
class AudioStreamInfoDto {
  const AudioStreamInfoDto({
    required this.codec,
    this.sampleRate,
    this.channels,
    this.bitrate,
  });

  /// Codec display name reported by `FFmpeg`.
  final String codec;

  /// Sample rate in hertz when known.
  final int? sampleRate;

  /// Channel count when known.
  final int? channels;

  /// Average stream bitrate when known.
  final int? bitrate;

  @override
  int get hashCode =>
      codec.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bitrate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioStreamInfoDto &&
          runtimeType == other.runtimeType &&
          codec == other.codec &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitrate == other.bitrate;
}

/// Codec capabilities reported by the configured native backend.
class BackendCapabilitiesDto {
  const BackendCapabilitiesDto({
    required this.ffmpegVersion,
    required this.h264Available,
    required this.aacAvailable,
    required this.mp3Available,
  });

  /// Human-readable `FFmpeg` library version.
  final String ffmpegVersion;

  /// Whether H.264 output is available on the active platform adapter.
  final bool h264Available;

  /// Whether native AAC output is available.
  final bool aacAvailable;

  /// Whether libmp3lame output is available.
  final bool mp3Available;

  @override
  int get hashCode =>
      ffmpegVersion.hashCode ^
      h264Available.hashCode ^
      aacAvailable.hashCode ^
      mp3Available.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackendCapabilitiesDto &&
          runtimeType == other.runtimeType &&
          ffmpegVersion == other.ffmpegVersion &&
          h264Available == other.h264Available &&
          aacAvailable == other.aacAvailable &&
          mp3Available == other.mp3Available;
}

/// Structured media failure crossing the generated FRB boundary.
class MediaBridgeError implements FrbException {
  const MediaBridgeError({required this.code, required this.diagnostic});

  /// Stable category used for presentation control flow and localization.
  final MediaBridgeErrorCode code;

  /// Diagnostic cause retained for structured development logs.
  final String diagnostic;

  @override
  int get hashCode => code.hashCode ^ diagnostic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaBridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          diagnostic == other.diagnostic;
}

/// Stable application failures exposed to the Flutter boundary.
enum MediaBridgeErrorCode {
  /// The source lacks a supported primary stream.
  unsupportedInput,

  /// The source path or container could not be opened.
  cannotOpenInput,

  /// A selected stream could not be decoded for metadata.
  decodeFailed,

  /// A required encoder is unavailable.
  encoderUnavailable,

  /// A trim range violates source bounds.
  invalidTrimRange,

  /// The destination exists without overwrite approval.
  outputExists,

  /// A protected temporary output could not be created.
  outputCreateFailed,

  /// Output data could not be written or committed.
  diskWriteFailed,

  /// Another conversion owns the exclusive job slot.
  jobActive,

  /// No matching active job exists.
  jobNotFound,

  /// Cooperative cancellation ended the operation.
  cancelled,

  /// The failure does not fit a stable application category.
  unexpected,
}

/// Canonical metadata for one successfully probed local source.
class MediaInfoDto {
  const MediaInfoDto({
    required this.path,
    required this.fileName,
    required this.fileSizeBytes,
    required this.durationMs,
    required this.format,
    this.video,
    this.audio,
    required this.availableOutputModes,
  });

  /// Losslessly represented canonical local path.
  final String path;

  /// Last path component for display.
  final String fileName;

  /// File size in bytes.
  final int fileSizeBytes;

  /// Container duration in integer milliseconds.
  final int durationMs;

  /// Container format reported by `FFmpeg`.
  final String format;

  /// Selected primary video stream when present.
  final VideoStreamInfoDto? video;

  /// Selected primary audio stream when present.
  final AudioStreamInfoDto? audio;

  /// Output recipes supported by the selected primary streams.
  final List<MediaOutputMode> availableOutputModes;

  @override
  int get hashCode =>
      path.hashCode ^
      fileName.hashCode ^
      fileSizeBytes.hashCode ^
      durationMs.hashCode ^
      format.hashCode ^
      video.hashCode ^
      audio.hashCode ^
      availableOutputModes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInfoDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          fileName == other.fileName &&
          fileSizeBytes == other.fileSizeBytes &&
          durationMs == other.durationMs &&
          format == other.format &&
          video == other.video &&
          audio == other.audio &&
          availableOutputModes == other.availableOutputModes;
}

/// Output recipes whose availability is determined by Rust metadata.
enum MediaOutputMode {
  /// H.264 video and AAC audio in MP4.
  videoWithAudio,

  /// H.264 video without audio in MP4.
  videoOnly,

  /// MP3 audio without video.
  audioOnly,
}

/// Primary video metadata safe to expose through FRB.
class VideoStreamInfoDto {
  const VideoStreamInfoDto({
    required this.codec,
    required this.width,
    required this.height,
    this.frameRate,
    this.bitrate,
    this.pixelFormat,
  });

  /// Codec display name reported by `FFmpeg`.
  final String codec;

  /// Display width in pixels.
  final int width;

  /// Display height in pixels.
  final int height;

  /// Frames per second when the source reports a valid rate.
  final double? frameRate;

  /// Average stream bitrate when known.
  final int? bitrate;

  /// Pixel format when known.
  final String? pixelFormat;

  @override
  int get hashCode =>
      codec.hashCode ^
      width.hashCode ^
      height.hashCode ^
      frameRate.hashCode ^
      bitrate.hashCode ^
      pixelFormat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoStreamInfoDto &&
          runtimeType == other.runtimeType &&
          codec == other.codec &&
          width == other.width &&
          height == other.height &&
          frameRate == other.frameRate &&
          bitrate == other.bitrate &&
          pixelFormat == other.pixelFormat;
}
