// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: public_member_api_docs

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_transcode_request`, `canonicalize_output_path`, `canonicalize_path`, `is_terminal`, `job_event_id`, `media_runtime`, `path_to_string`, `subscribe`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BridgeJobEventSink`, `EventDelivery`, `MediaRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `emit`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_from`, `try_from`, `try_from`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`

/// Initializes the process-wide `FFmpeg` adapter and reports its capabilities.
///
/// # Errors
///
/// Returns a structured failure when the repository-built `FFmpeg` libraries
/// cannot initialize.
Future<BackendCapabilitiesDto> initializeBackend() =>
    MediaForgeRustLib.instance.api.crateApiMediaInitializeBackend();

/// Canonicalizes and probes one regular local media file on FRB's Rust executor.
///
/// # Errors
///
/// Returns a structured application failure when the path cannot be
/// canonicalized, the input is unsupported, or `FFmpeg` cannot inspect it.
Future<MediaInfoDto> probeMedia({required String path}) =>
    MediaForgeRustLib.instance.api.crateApiMediaProbeMedia(path: path);

/// Proposes a destination beside a canonical source for one supported recipe.
///
/// # Errors
///
/// Returns a structured path failure when the source cannot be canonicalized or
/// the resulting destination cannot be represented losslessly for Dart.
Future<String> defaultOutputPath({
  required String path,
  required MediaOutputMode mode,
}) => MediaForgeRustLib.instance.api.crateApiMediaDefaultOutputPath(
  path: path,
  mode: mode,
);

/// Validates and starts one primary Video + Audio conversion.
///
/// # Errors
///
/// Returns a stable application failure for stale paths, unsupported mode,
/// invalid trim, unavailable encoders, or an already active job.
Future<JobSnapshotDto> startTranscode({
  required StartTranscodeRequestDto request,
}) => MediaForgeRustLib.instance.api.crateApiMediaStartTranscode(
  request: request,
);

/// Registers the process's current Flutter subscriber for application events.
///
/// The stream remains open for the process lifetime. Re-registering replaces a
/// stale presentation subscriber and replays any retained terminal event.
Stream<JobEventDto> jobEvents() =>
    MediaForgeRustLib.instance.api.crateApiMediaJobEvents();

/// Primary audio metadata safe to expose through FRB.
class AudioStreamInfoDto {
  const AudioStreamInfoDto({
    required this.codec,
    this.sampleRate,
    this.channels,
    this.bitrate,
  });

  /// Codec display name reported by `FFmpeg`.
  final String codec;

  /// Sample rate in hertz when known.
  final int? sampleRate;

  /// Channel count when known.
  final int? channels;

  /// Average stream bitrate when known.
  final int? bitrate;

  @override
  int get hashCode =>
      codec.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bitrate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioStreamInfoDto &&
          runtimeType == other.runtimeType &&
          codec == other.codec &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitrate == other.bitrate;
}

/// Codec capabilities reported by the configured native backend.
class BackendCapabilitiesDto {
  const BackendCapabilitiesDto({
    required this.ffmpegVersion,
    required this.h264Available,
    required this.aacAvailable,
    required this.mp3Available,
  });

  /// Human-readable `FFmpeg` library version.
  final String ffmpegVersion;

  /// Whether H.264 output is available on the active platform adapter.
  final bool h264Available;

  /// Whether native AAC output is available.
  final bool aacAvailable;

  /// Whether libmp3lame output is available.
  final bool mp3Available;

  @override
  int get hashCode =>
      ffmpegVersion.hashCode ^
      h264Available.hashCode ^
      aacAvailable.hashCode ^
      mp3Available.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackendCapabilitiesDto &&
          runtimeType == other.runtimeType &&
          ffmpegVersion == other.ffmpegVersion &&
          h264Available == other.h264Available &&
          aacAvailable == other.aacAvailable &&
          mp3Available == other.mp3Available;
}

/// Tagged application event delivered to the Flutter conversion controller.
class JobEventDto {
  const JobEventDto({
    required this.kind,
    required this.jobId,
    this.percent,
    this.processedMs,
    this.totalMs,
    this.framesPerSecond,
    this.speed,
    this.outputPath,
    this.error,
  });

  /// Discriminator controlling which optional payload fields are meaningful.
  final JobEventKindDto kind;

  /// Job that produced the event.
  final int jobId;

  /// Completion percentage for [`JobEventKindDto::Progress`].
  final double? percent;

  /// Processed time for [`JobEventKindDto::Progress`].
  final int? processedMs;

  /// Selected duration for [`JobEventKindDto::Progress`].
  final int? totalMs;

  /// Current frame rate for [`JobEventKindDto::Progress`] when available.
  final double? framesPerSecond;

  /// Current realtime multiplier for [`JobEventKindDto::Progress`] when available.
  final double? speed;

  /// Final destination for [`JobEventKindDto::Completed`].
  final String? outputPath;

  /// Structured failure for [`JobEventKindDto::Failed`].
  final MediaBridgeError? error;

  @override
  int get hashCode =>
      kind.hashCode ^
      jobId.hashCode ^
      percent.hashCode ^
      processedMs.hashCode ^
      totalMs.hashCode ^
      framesPerSecond.hashCode ^
      speed.hashCode ^
      outputPath.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JobEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          jobId == other.jobId &&
          percent == other.percent &&
          processedMs == other.processedMs &&
          totalMs == other.totalMs &&
          framesPerSecond == other.framesPerSecond &&
          speed == other.speed &&
          outputPath == other.outputPath &&
          error == other.error;
}

/// Discriminator controlling the meaningful fields in [`JobEventDto`].
enum JobEventKindDto {
  /// The application reserved the exclusive worker slot.
  preparing,

  /// The backend emitted a throttled monotonic progress sample.
  progress,

  /// The final destination was committed successfully.
  completed,

  /// Cooperative cancellation and cleanup completed.
  cancelled,

  /// A non-cancellation failure and cleanup completed.
  failed,
}

/// Plain snapshot returned immediately after the application reserves a job.
class JobSnapshotDto {
  const JobSnapshotDto({
    required this.jobId,
    required this.state,
    required this.inputPath,
    required this.outputPath,
  });

  /// Process-local job identifier used to correlate events.
  final int jobId;

  /// Current lifecycle state.
  final JobStateDto state;

  /// Canonical source path reserved by the job.
  final String inputPath;

  /// Canonical destination path reserved by the job.
  final String outputPath;

  @override
  int get hashCode =>
      jobId.hashCode ^
      state.hashCode ^
      inputPath.hashCode ^
      outputPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JobSnapshotDto &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          state == other.state &&
          inputPath == other.inputPath &&
          outputPath == other.outputPath;
}

/// Lifecycle state returned with a conversion snapshot.
enum JobStateDto {
  /// No job has started.
  idle,

  /// A worker owns the job and is opening media resources.
  preparing,

  /// The backend is producing output.
  running,

  /// The destination was committed successfully.
  completed,

  /// Cooperative cancellation ended the operation.
  cancelled,

  /// A non-cancellation error ended the operation.
  failed,
}

/// MP3 quality values retained in the stable conversion request contract.
enum MediaAudioQuality {
  /// 256 kbps MP3.
  high,

  /// 192 kbps MP3.
  medium,

  /// 128 kbps MP3.
  low,
}

/// Structured media failure crossing the generated FRB boundary.
class MediaBridgeError implements FrbException {
  const MediaBridgeError({required this.code, required this.diagnostic});

  /// Stable category used for presentation control flow and localization.
  final MediaBridgeErrorCode code;

  /// Diagnostic cause retained for structured development logs.
  final String diagnostic;

  @override
  int get hashCode => code.hashCode ^ diagnostic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaBridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          diagnostic == other.diagnostic;
}

/// Stable application failures exposed to the Flutter boundary.
enum MediaBridgeErrorCode {
  /// The source lacks a supported primary stream.
  unsupportedInput,

  /// The source path or container could not be opened.
  cannotOpenInput,

  /// A selected stream could not be decoded for metadata.
  decodeFailed,

  /// A required encoder is unavailable.
  encoderUnavailable,

  /// A trim range violates source bounds.
  invalidTrimRange,

  /// The destination exists without overwrite approval.
  outputExists,

  /// A protected temporary output could not be created.
  outputCreateFailed,

  /// Output data could not be written or committed.
  diskWriteFailed,

  /// Another conversion owns the exclusive job slot.
  jobActive,

  /// No matching active job exists.
  jobNotFound,

  /// Cooperative cancellation ended the operation.
  cancelled,

  /// The failure does not fit a stable application category.
  unexpected,
}

/// Canonical metadata for one successfully probed local source.
class MediaInfoDto {
  const MediaInfoDto({
    required this.path,
    required this.fileName,
    required this.fileSizeBytes,
    required this.durationMs,
    required this.format,
    this.video,
    this.audio,
    required this.availableOutputModes,
  });

  /// Losslessly represented canonical local path.
  final String path;

  /// Last path component for display.
  final String fileName;

  /// File size in bytes.
  final int fileSizeBytes;

  /// Container duration in integer milliseconds.
  final int durationMs;

  /// Container format reported by `FFmpeg`.
  final String format;

  /// Selected primary video stream when present.
  final VideoStreamInfoDto? video;

  /// Selected primary audio stream when present.
  final AudioStreamInfoDto? audio;

  /// Output recipes supported by the selected primary streams.
  final List<MediaOutputMode> availableOutputModes;

  @override
  int get hashCode =>
      path.hashCode ^
      fileName.hashCode ^
      fileSizeBytes.hashCode ^
      durationMs.hashCode ^
      format.hashCode ^
      video.hashCode ^
      audio.hashCode ^
      availableOutputModes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInfoDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          fileName == other.fileName &&
          fileSizeBytes == other.fileSizeBytes &&
          durationMs == other.durationMs &&
          format == other.format &&
          video == other.video &&
          audio == other.audio &&
          availableOutputModes == other.availableOutputModes;
}

/// Output recipes whose availability is determined by Rust metadata.
enum MediaOutputMode {
  /// H.264 video and AAC audio in MP4.
  videoWithAudio,

  /// H.264 video without audio in MP4.
  videoOnly,

  /// MP3 audio without video.
  audioOnly,
}

/// Plain conversion request accepted from Flutter presentation state.
class StartTranscodeRequestDto {
  const StartTranscodeRequestDto({
    required this.inputPath,
    required this.outputPath,
    required this.mode,
    required this.audioQuality,
    required this.startMs,
    required this.endMs,
    required this.overwrite,
  });

  /// Canonical source path previously returned by [`probe_media`].
  final String inputPath;

  /// Destination path proposed by [`default_output_path`].
  final String outputPath;

  /// Requested output recipe.
  final MediaOutputMode mode;

  /// MP3 quality retained for the future audio-only workflow.
  final MediaAudioQuality audioQuality;

  /// Inclusive trim start in integer milliseconds.
  final int startMs;

  /// Exclusive trim end in integer milliseconds.
  final int endMs;

  /// Whether an existing destination may be replaced after success.
  final bool overwrite;

  @override
  int get hashCode =>
      inputPath.hashCode ^
      outputPath.hashCode ^
      mode.hashCode ^
      audioQuality.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      overwrite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartTranscodeRequestDto &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          outputPath == other.outputPath &&
          mode == other.mode &&
          audioQuality == other.audioQuality &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          overwrite == other.overwrite;
}

/// Primary video metadata safe to expose through FRB.
class VideoStreamInfoDto {
  const VideoStreamInfoDto({
    required this.codec,
    required this.width,
    required this.height,
    this.frameRate,
    this.bitrate,
    this.pixelFormat,
  });

  /// Codec display name reported by `FFmpeg`.
  final String codec;

  /// Display width in pixels.
  final int width;

  /// Display height in pixels.
  final int height;

  /// Frames per second when the source reports a valid rate.
  final double? frameRate;

  /// Average stream bitrate when known.
  final int? bitrate;

  /// Pixel format when known.
  final String? pixelFormat;

  @override
  int get hashCode =>
      codec.hashCode ^
      width.hashCode ^
      height.hashCode ^
      frameRate.hashCode ^
      bitrate.hashCode ^
      pixelFormat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoStreamInfoDto &&
          runtimeType == other.runtimeType &&
          codec == other.codec &&
          width == other.width &&
          height == other.height &&
          frameRate == other.frameRate &&
          bitrate == other.bitrate &&
          pixelFormat == other.pixelFormat;
}
