[package]
name = "mediaforge-flutter-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge.workspace = true
mediaforge-application.workspace = true
mediaforge-core.workspace = true
mediaforge-ffmpeg.workspace = true

[lints]
workspace = true
