[package]
name = "mediaforge-ffmpeg"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ffmpeg-next = { version = "9.0.0", default-features = false, features = [
  "codec",
  "filter",
  "format",
  "software-resampling",
  "software-scaling",
] }
mediaforge-core.workspace = true
rustix.workspace = true

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
